-- Create the states DB table in teh DB hbtn_0d_usa
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(
	id INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
	name VARCHAR(256) NOT NULL
);
